### ISSUE TITLE
hi，guys 

### ISSUE THREAD

**Issue by mangopool** [CalexCore/Amity-Coin#1]
i'm chinese boy,it's happy to meet you。Can you give me your email address? I want to follow up on your project. Thank you

**Comment by Amity-Core** [comment]
You’re in the wrong repo if you’re looking for AmityCoin.
This repo is trying to get AmityCoin from a BCN fork to a TRTL fork.
You can contact us on here, Twitter (@AmityCore) and discord (https://discord.gg/CMetnjX)

Amity Jack
